### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by ScienceZone** [BensonLaur/BesLyric#1]
有些歌词为了显示所有的汉字需要以UTF-8编码方式保存，但是程序会显示乱码，希望解决一下，谢谢！

**Comment by BensonLaur** [comment]
BesLyric v1.0.1新鲜出炉！ 歌词原文件在原来支持 ascii 码的基础上，支持windows文本另外3种编码：Unicode 、Unicode little endian 、UTF-8
