### ISSUE TITLE
改进歌词制作和歌词预览的功能

### ISSUE THREAD

**Issue by onemans-battle** [BensonLaur/BesLyric#21]
此软件令我最心动的莫过是上箭头按键制作方式的方便性了。然而在一些细节上令我觉得不尽理想。

我认为开发软件，目的之一在于隐藏底层细节从而避免繁琐，而在歌词预览界面却意外的看到了原始（底层）的制作模式---打开纯文本手动编写时间标签。然而微调如果是在歌词制作中，问题将迎刃而解。
歌词制作时无法快进，歌词预览时无法微调（其实微调的本质也是制作）歌词。歌词制作的过程也可以视作歌词预览的过程，我认为两个模块是互补的，希望作者考虑一下集成的可能性和可行性。预览中的快进弥补了制作时无法快进。把没有时间标签的txt、待微调的lrc都视做lrc，在预览中制作歌词应该是种理想状态。

我设想的集成后的主要制作功能/按键: 
- 上箭头功能不变用来真正的**制作**歌词(添加时间标签)；
- 左右方向键用来根据时间快进、回退进行**预览**；
- AD左右键用来根据每句歌词来**预览**。

我认为这样一来，不论是初步制作还是后期微调都极为方便

**Comment by BensonLaur** [comment]
首先十分的感谢在此提出你的想法和建议，我十分地赞同你关于软件的目的之一是为了隐藏底层繁琐细节的想法，事实上这个软件的诞生也是出于此想法。
对提出的想法，回复如下：

**1、关于在歌词制作过程中加入快进功能**

歌词制作的过程，本质上是一个摸石头过河的过程，摸到前面的踏实的石头就踏出去一步，摸到尖刺或深坑就撤销重新摸，直到摸到河的彼岸。  在这个过程中， 重新摸（Beslyric的B键(Back)） 是【调整】的【关键】， 如果下一块石头没摸着就往前大跨一步，刚好踩到踏实的石头自然没事，可以继续摸索下一步， 但是遇到坑了， 还是需要收回来【调整】。
结果我们应该可以看到， 在摸石头过河的过程中， 贸然跨出一大步， 不仅无法对【调整】作出贡献， 相反， 还有可能会因此花更长的时间过河。
故与之同理，在制作歌词的过程中，快进应该作用不大。

**2、考虑歌词【制作】和【预览】集成的可能性**

愚以为，制作歌词的过程 和 预览歌词的 过程的本质是不一样的，过程也应该区别对待。
制作歌词时，我们无法知道纯歌词将出现的具体位置，这个过程只能稳扎稳打，不具备前瞻性、跳跃性，但是出现错误时有较大的灵活性。
预览歌词时，每一句歌词该出现在那个时间点则已经清楚，具有全局可确定性，但是相对的， 灵活性较弱 （预览过程中， 我们很难去除某句词的时间标签， 而为其贴上另一个）。

**3、在预览中制作歌词**

基于第2点的想法，在灵活性较弱的预览过程中，制作过程将难以直接实现，这一点原因将在第4点体现。

**4、关于你提供的制作功能/按键的设想**

- ←→方向键的 → 如何用于预览没有时间标签的歌词

-  同样 A D 方向键的 D 键如何用来预览下一句没有时间标签的歌词

-  ↑ 键作为添加时间标签，在这种设计方案中， 如何去除已经添加的错误不想要的时间标签呢（现在是用B回退来去除错误的时间标签）
 
 我想将【制作】和【预览】放在一起考虑将无法很好的解决这些困惑

 **5、关于 【微调时间轴】打开纯文本的设计的困惑**
 
 我们确实会看到这样的设计有不好的地方，往前看，确实这样的设计不尽人意；但是 往后看， 可能就会明白为什么会有这个设计。 
 其实一开始，我制作的第一个lrc歌词是纯手打的；后来刚开发了这个软件， 制作时是没有回退【B】功能的， 但是相比纯手打， 已经方便很多； 再到后来陆陆续续收到建议， 针对【微调】这个需要， 添加了回退【B】功能, 以及在设置添加了提前毫秒数， 解决了这个问题。现在， 制作过程的【B】回退功能基本解决了【微调问题】， 但此【微调时间轴】纯手打接口还是保留了，也算是多一个选择吧。

虽然这个建议不会采纳，那时非常感谢您认真的反馈！

**Comment by onemans-battle** [comment]
感谢您的解答，从您的解答中，我加深了对自己想法的理解。
虽还是显得粗糙，但我尽自己现有的水平表述如下。

#### 1、为什么【预览】也可视为【制作】？
预览目的在于验证歌词【制作】中时间标签的准确性，而且比【制作】更精准："嗯？我刚才按↑似乎慢了些，好，B回退重新打时间标签 "，而通过【预览】中滚动的歌词很明确地判断标签准确与否。因此微调在所难免。也就是说，歌词【预览】的本质在某种程度上与【制作】相同：都是对时间标签进行操作。如此看来，【预览】是【制作】的一部分，也是对【制作】的补足。当然也有一种视角（本软件就是如此？）：制作过程分"摸石头过河"的歌词大体时间的定稿和最终的修正微调两种阶段。但现软件似乎把两种阶段都放进【制作】里，可正如前面所说，【制作】中对错误的定位并不令人放心。虽然如此，此软件B键与提前毫秒数现已很好地充当了后期微调。

#### 2、关于歌词【制作】的快进
按照"摸石头过河"模型，您把歌词当作石头，那么音乐就是水，石头间存在着水，且石头间隔（伴奏）有长有短。如果我看见了间隔很长的端倪，越过(快进)是可以接受的。

#### 3、关于我的设想的功能说明
- ←→方向键：根据时间回退、快进播放音乐并定位歌词，在初步"摸石头"过程中，←充当了B键的角色。→一直定位到最近的没有时间标签的位置为止，这样能够快进且确保↑键功能的便捷。
- A D 方向键：根据歌词的时间标签来回退、快进音乐。这里主要用来预览和后期微调。
- ↑ 键作为添加/覆盖时间标签。
下面是在两种场景中对上述功能的使用
- 只有歌词时：听到了对应歌词的人声，好，我通过↑来打上时间标签，依旧如原来那般便捷。啊，这里有很长的伴奏，我使用→键来快进并确保最近没有时间标签歌词在当前行保持待命。啊，我快进多了，我使用←键回退，并保证歌词待命。
- 添加了歌词，但需准确的预览并修正：我既可通过←→也可通过A D 来滚动歌词，但A D键因为是根据歌词进行滚动所以查看歌词错误变得明显许多。因此我倾斜于使用A D键。如果我遇到了错误标签，我直接使用↑覆盖已有的时间标签来微调。

**Comment by onemans-battle** [comment]
感谢您的解答，从您的解答中，我加深了对自己想法和软件的理解。
虽还是显得粗糙，但我尽自己现有的水平表述如下。
此次与其说是集成的想法，不如说是关于改进的想法。
#### 1、为什么【预览】也可视为【制作】？
预览目的在于验证歌词【制作】中时间标签的准确性，而且比【制作】的凭感觉来微调更精准："嗯？我刚才按↑似乎慢了些，好，B回退重新打时间标签 "，而通过【预览】中滚动的歌词很明确地判断标签准确与否。因此微调在所难免。也就是说，歌词【预览】的本质在某种程度上与【制作】相同：都是对时间标签进行操作。如此看来，【预览】是【制作】的一部分，也是对【制作】的补足。因此制作可以分两阶段：时间标签的大体定稿即现有的【制作】、最终的微调修正即现有的【预览】。将两阶段暂称作：【时间定稿】、【预览微调】。

#### 2、关于歌词【制作】的快进
按照"摸石头过河"模型，您把歌词当作石头，那么音乐就是水，石头间存在着水，且石头间隔（伴奏）有长有短。如果我摸着了间隔很长的端倪，越过(快进)是可以接受的。

#### 3、关于我的设想的功能说明
- ←→方向键：根据时间回退、快进播放音乐，不存在时间标签定位问题。
- ↑ 键作为添加/覆盖时间标签。
- 【预览微调】阶段独有：A D 方向键：根据歌词的时间标签来回退、快进音乐。这里主要用来预览和后期微调。
- 【时间定稿】阶段都有：b键依旧用来回退进行“大体”上的修改。
##### 下面是在两种场景中对上述功能的使用
- 只有歌词时：遇到很长的伴奏，使用→键来快进伴。快进多了，使用←键回退。歌词时间明显错了，按B键回退定位歌词重做。
- 添加了歌词，但需准确的预览并修正：我既可通过←→也可通过A D 来**预览**滚动的歌词，但A D键因为是根据歌词进行滚动所以查看歌词错误变得明显许多。因此我倾斜于使用A D键。如果我遇到了错误标签需要微调，我则先使用←→来**定位时间**，再使用↑覆盖已有的时间标签来微调。

**Comment by BensonLaur** [comment]
听完建议，我想到的问题是 如何用 ↑ 键来覆盖时间标签，另外我担心的一个问题是 这样的各种按键的安排是否为使得操作复杂化。
我想这是我开始动手会面临的实践和想法上的阻碍，这个项目的初衷是简单易用，不知效果会怎么样。这是我会考虑的。
从你的描述中，我隐约觉得您应该是有开发经验的，不知道有没有兴趣尝试实现你的想法呢？或许可以push一个request，我clone 你的分支跑一下觉得可以我是会合并的，或者再不济，你也可以尝到自己耕耘的果实。 不知有没有这个意愿呢 :)

**Comment by onemans-battle** [comment]
恩，确实会复杂了，我的想法还有需要改进的地方。
因为我没什么开发经验，自己写可能稍显困难。
这个可以先放着或者关掉，我不清楚有没能力自己写。
