### ISSUE TITLE
希望制作歌词时程序自动保存制作进度

### ISSUE THREAD

**Issue by onemans-battle** [BensonLaur/BesLyric#22]
间隔1分钟或者每制作了5句歌词之类的。

**Comment by BensonLaur** [comment]
个人觉得，自动保存的意义在这里可能无法体现。
我对自动保存的理解是，在进行耗时长、数据恢复代价大的情况下，为了减小由于 软件意外奔溃（比如 各各种设计工作、代码编写工作过程中的情况），通讯突然中断（比如写博客过程由于网络问题中断连接 或意外关闭）等情况 带来的损失，会采用自动保存的设计。
这里制作歌词耗时段，且恢复代价小，自动保存进度的设计应该是比较缺乏实用性的。

**Comment by onemans-battle** [comment]
此建议源于无法在制作途中暂时保存lrc文件。也许正如您所说，几分钟音乐的歌词制作代价很小，所以不需要保存”半成品“吧。况且半成品lrc是不被歌词【制作】所接纳的：不识别时间标签。
