### ISSUE TITLE
提两建议

### ISSUE THREAD

**Issue by wujiyu115** [BensonLaur/BesLyric#24]
1 _滚动预览可以自动播放歌曲，不用点开始播放
2 制作时前奏太长的歌曲可以快进,最好是可以点进度条定位

**Comment by BensonLaur** [comment]
感谢反馈！
1、我想你的意思应该是在制作完之后，点击“滚动预览”切换页面后自动播放歌曲，这一点想法挺不错的，已纳入考虑！
2、制作时快进或任意定位这一点，已有人在 Issues #21 提过类似建议，并给出回复可以参考一下看看。虽然在你说的场景下有一定的作用，但是由于考虑到该功能实用性（以及会不会影响制作体验等） 和按键安排问题等，应该是不会考虑进去的。

**Comment by BensonLaur** [comment]
最新版本已加入【点击“滚动预览”切换页面后自动播放歌曲】功能

**Comment by hentaiisme** [comment]
是优秀的同学

**Comment by CollinChan** [comment]
nice
