### ISSUE TITLE
ffmpeg安装在其他目录下时不可用

### ISSUE THREAD

**Issue by uminosaki** [BensonLaur/BesLyric#30]
我曾经因为别的原因安装过ffmpeg并设置了环境变量，但是在使用这个软件时似乎一直执着于要把ffmpeg放在安装目录下

**Comment by BensonLaur** [comment]
软件没有考虑用户自己安装的 ffmpeg 的情况。

之前使用Windows mci 接口播放，后来发现一个很严重的问题，有些mp3使用mci接口播放竟然多出了前面几秒，这对于制作歌词来说是不可接受的，然后为了快速弥补这个问题，于是后来直接是除wav之外的都用 ffmpeg.exe 先转换为 mci 接受的wav格式。

然后使用的是固定路径下的 ffmpeg.exe

**Comment by pzhlkj6612** [comment]
复制一份 FFmpeg 吧，因为这是硬编码的路径：

https://github.com/Beslyric-for-X/BesLyric/blob/4c1fec6ca29e49e601bf3f8990f74eb96b95e790/BesLyric/entity/CheckIntegrityThread.cpp#L149-L150

https://github.com/Beslyric-for-X/BesLyric/blob/4c1fec6ca29e49e601bf3f8990f74eb96b95e790/BesLyric/entity/CheckIntegrityThread.cpp#L445-L446

https://github.com/Beslyric-for-X/BesLyric/blob/b56318c2a29e13657ca7de7921c453a1ea64af76/BesLyric/PageResult.cpp#L469

https://github.com/Beslyric-for-X/BesLyric/blob/b56318c2a29e13657ca7de7921c453a1ea64af76/BesLyric/PageMaking.cpp#L599

**Comment by uminosaki** [comment]
感谢回复，已经复制了一份 ffmpeg.exe 放在了对应目录下。
